#!/usr/bin/env bash
# Generates /app/config.toml from env vars on container start, then execs the daemon.
# Supports up to 4 sources: SOURCE_{1..4}_SLUG / _SPACE / _BOT_TOKEN
#                           / _TRANSCRIPTION_PROVIDER (mistral|openai|none, default none)
#                           / _TRANSCRIPTION_TOKEN
set -euo pipefail

CONFIG_PATH="${CONFIG_PATH:-/app/config.toml}"
DB_PATH="${DB_PATH:-/data/data-heap.sqlite}"
HTTP_ADDR="${HTTP_ADDR:-0.0.0.0:8080}"

mkdir -p "$(dirname "$DB_PATH")"

{
  echo "# auto-generated by entrypoint.sh on container start"
  echo "[daemon]"
  echo "database_path = \"$DB_PATH\""
  echo "http_addr = \"$HTTP_ADDR\""
  echo
} > "$CONFIG_PATH"

emitted=0
for i in 1 2 3 4; do
  slug_var="SOURCE_${i}_SLUG"
  space_var="SOURCE_${i}_SPACE"
  token_var="SOURCE_${i}_BOT_TOKEN"
  provider_var="SOURCE_${i}_TRANSCRIPTION_PROVIDER"
  tr_token_var="SOURCE_${i}_TRANSCRIPTION_TOKEN"

  slug="${!slug_var-}"
  space="${!space_var-}"
  token="${!token_var-}"
  provider="${!provider_var-none}"
  tr_token="${!tr_token_var-}"

  if [[ -z "$slug" && -z "$space" && -z "$token" ]]; then
    continue
  fi

  if [[ -z "$slug" || -z "$space" || -z "$token" ]]; then
    echo "entrypoint: SOURCE_${i}_* incomplete (need slug, space, bot_token)" >&2
    exit 1
  fi

  {
    echo "[[sources]]"
    echo "slug = \"$slug\""
    echo "space = \"$space\""
    echo "bot_token = \"$token\""
    echo "transcription_provider = \"$provider\""
    if [[ "$provider" != "none" && -n "$tr_token" ]]; then
      echo "transcription_token = \"$tr_token\""
    fi
    echo
  } >> "$CONFIG_PATH"
  emitted=$((emitted + 1))
done

if [[ "$emitted" -eq 0 ]]; then
  echo "entrypoint: no sources configured. Set at least SOURCE_1_SLUG / _SPACE / _BOT_TOKEN in .env" >&2
  exit 1
fi

echo "entrypoint: wrote $CONFIG_PATH with $emitted source(s); db=$DB_PATH; http=$HTTP_ADDR"
exec data-heap "$CONFIG_PATH"
